--- #YAML:1.0
name:               XML-IODEF-Simple-Plugin-RI_RESTRICTION
version:            0.00_01
abstract:           Perl extension for blah blah blah
author:
    - Wes Young <wes@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
